services:
  # region storage
  region1:
    image: chrislusf/seaweedfs
    command: "server -s3 -dir /data"
    ports:
      - "8333:8333"
      - "9321:9321"
    volumes:
      - region1:/data
    environment:
      S3_ACCESS_KEY: argon
      S3_SECRET_KEY: argon
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9321/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  region2:
    image: chrislusf/seaweedfs
    command: "server -s3 -dir /data"
    ports:
      - "8334:8333"
      - "9322:9321"
    volumes:
      - region2:/data
    environment:
      S3_ACCESS_KEY: argon
      S3_SECRET_KEY: argon
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9321/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  # endregion storage
  # region databases
  scylla:
    image: scylladb/scylla:latest
    volumes:
      - scylla:/var/lib/scylla
    command: --smp 1 --memory 264M --overprovisioned 1 --developer-mode 1
    ports:
      - "9042:9042"
      - "9160:9160"
    environment:
      SCYLLA_CLUSTER_NAME: 'scylla_cluster'
      SCYLLA_SEEDS: 'scylla'
  pg:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kineticafs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  # endregion databases
  # region application
  # kineticafs:
  #   build: .
  #   tty: true
  #   stdin_open: true
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - region1
  #     - region2
  #     - scylla
  #     - pg
  #   environment:
  #     - KINETICAFS_SCYLLA=scylla:9042
  #     - KINETICAFS_POSTGRES=postgres://postgres:postgres@pg:5432/kineticafs?sslmode=disable
  #   restart: unless-stopped
  # endregion application
volumes:
  pgdata: {}
  region1: {}
  region2: {}
  scylla: {}
