services:
  region1:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    volumes:
      - ./data/region1:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
  region2:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    volumes:
      - ./data/region2:/data
    ports:
      - "9002:9002"
      - "9003:9003"
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9002'
      MINIO_CONSOLE_ADDRESS: ':9003'
    command: minio server /data
  scylla:
    image: scylladb/scylla:latest
    volumes:
      - ./data/scylla:/var/lib/scylla
    ports:
      - "9042:9042"
      - "9160:9160"
    environment:
      SCYLLA_CLUSTER_NAME: 'scylla_cluster'
      SCYLLA_SEEDS: 'scylla'