# KineticaFS Configuration File

# Server configuration
server: false         # Set to true to run as server
port: 3000           # Port on which the server will listen

# Database configuration
database: "scylla"      # Database backend type (scylla, postgres etc.)

# ScyllaDB configuration
scylla: "localhost:9042"  # ScyllaDB connection string (host:port or host1:port1,host2:port2)
scylla_keyspace: "kineticafs"  # Optional: Custom keyspace name (defaults to "kineticafs")

# PostgreSQL configuration
postgres: "postgres://postgres:postgres@localhost:5432/kineticafs?sslmode=disable"           # PostgreSQL connection string (host:port or full URL)

# Authentication
token: ""            # Authorization token (leave empty for no token)

# Front-end static file serving
front-end-path: "/var/www"   # Path to front-end folder containing index.html and assets

# Region configuration
region: "./regions.json"     # Path to regions configuration file

# Environment variable prefix: KINETICAFS_
migrate: false       # Set to true to run database migrations
mock: false          # Set to true to enable mock test data

# Environment variable prefix: KINETICAFS_
# Examples:
# KINETICAFS_SERVER=true
# KINETICAFS_PORT=8080
# KINETICAFS_DATABASE=postgres
# KINETICAFS_SCYLLA=192.168.1.100:9042
# KINETICAFS_SCYLLA_KEYSPACE=my_keyspace
# KINETICAFS_POSTGRES=postgres://user:pass@host:5432/dbname?sslmode=disable
# KINETICAFS_TOKEN=your-auth-token
# KINETICAFS_MIGRATE=true
# KINETICAFS_MOCK=true
# KINETICAFS_FRONT-END-PATH=/your/custom/path
# KINETICAFS_REGION=./my-regions.json